# Generated by Django 4.0.1 on 2022-02-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_customer_date_added_customer_phone_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Biżuteria złota', 'Biżuteria złota'), ('Biżuteria srebrna', 'Biżuteria srebrna'), ('Biżuteria stalowa', 'Biżuteria stalowa'), ('Zegarki', 'Zegarki'), ('Monety', 'Monety'), ('Upominki', 'Upominki'), ('Obrączki', 'Obrączki'), ('Akcesoria', 'Akcesoria')], max_length=200, null=True),
        ),
    ]
