# Generated by Django 4.0.1 on 2022-02-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_order',
            field=models.DateTimeField(auto_now_add=True, choices=[('W toku', 'W toku'), ('Realizowanie', 'Realizowanie'), ('Zakończone', 'Zakończone')]),
        ),
    ]
