# Generated by Django 4.0.1 on 2022-02-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_order_date_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_order',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, choices=[('W toku', 'W toku'), ('Realizowanie', 'Realizowanie'), ('Zakończone', 'Zakończone')]),
        ),
    ]
