# Generated by Django 4.0.1 on 2022-02-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_orderitem_status_alter_orderitem_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('W toku', 'W toku'), ('Realizowanie', 'Realizowanie'), ('Zakończone', 'Zakończone')], max_length=200, null=True),
        ),
    ]
