# Generated by Django 4.0.1 on 2022-03-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Przyjęte', 'Przyjęte'), ('Realizowanie', 'Realizowanie'), ('Zakończone', 'Zakończone')], max_length=200, null=True),
        ),
    ]
